name: Continuous Integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name : Python Lint Code Scanning Action
      #  uses: advanced-security/python-lint-code-scanning-action@v1.1.2
      #  with:
      #    linter: pylint
      #- name: Run Python black code formatter
      #  uses: DataDog/action-py-black-formatter@v2.5